fire = ['Flareon', 
        'Slugma', 
        'Chimchar', 
        'Growlithe',
        'Ponyta',
        'Cyndaquil',
        'Magby',
        'Torchic',
        'Torkoal',
        'Castform',
        'Tepig',
        'Pansear']

water = ['Poliwag', 
         'Psyduck', 
         'Starmie', 
         'Seel',
         'Horsea',
         'Magikarp',
         'Vaporeon',
         'Octillery',
         'Mudkip',
         'Corphish',
         'Oshawott',
         'Froakie']

grass = ['Seedot',
         'Snivy',
         'Skiddo',
         'Hoppip',
         'Celebi',
         'Treecko',
         'Chikorita',
         'Cherubi',
         'Leafeon',
         'Applin',
         'Bounsweet',
         'Sunflora']